### ISSUE TITLE
Feature request: Commit-creating flag akin to `nix flake update --commit-lock-file`

### ISSUE THREAD

**Issue by TLATER** [berberman/nvfetcher#11]
I'd enjoy a flag such as `nvfetcher --commit-changes` that creates a commit with the changelog that is dumped with `-l`.

I caught myself writing [a script](https://github.com/TLATER/dotfiles/blob/master/dotfiles/bin/commit-nvfetcher) to do this, and almost abstracting it out into its own flake because I will keep reusing it, but it might be better to just have this upstream :)

**Comment by TLATER** [comment]
Happy to hear any thoughts, I've spent no time thinking about how to implement this in this project, so feel free to tell me off for asking for the impossible.

**Comment by blaggacao** [comment]
Nice, I think I'll steal that right away for [`divnix/bud`](https://github.com/divnix/bud/tree/main/scripts)

**Comment by berberman** [comment]
Hi @TLATER, thanks for your feature request. Actually I'm doing this in my flakes repo:
* Write changelog to `COMMIT_MSG` in github actions: https://github.com/berberman/flakes/blob/91590ac6594ebde62129fac7c11e53b841beb47b/Update.hs#L57-L70
* Use [`stefanzweifel/git-auto-commit-action`](https://github.com/stefanzweifel/git-auto-commit-action) to perform the commit if `COMMIT_MSG` exists: https://github.com/berberman/flakes/blob/91590ac6594ebde62129fac7c11e53b841beb47b/.github/workflows/nvfetcher.yaml#L35-L39

So it won't be hard to add a CLI option to post-run `git commit`. There might be a question that should `_sources/.shake.database` be committed? If you run `nvfetcher` and do the auto commit in CI like me, you need to commit the shake db as well. Otherwise, it should be fine to keep it locally. The idea here is that `.shake.database` records the state of `nvfetcher`, so without it, `nvfetcher` may do duplicate works and produce incorrect changelog.

**Comment by TLATER** [comment]
I believe the database should be committed, too, if there was a change. I'd like to skim the commit messages to check what updated, so that I can check upstream and see if the updates might be bad.

What I discovered while writing my script is that the database contents also change if there are no changes to the sources. I don't think this should be committed, do you know why that happens? Simply a timestamp?

**Comment by berberman** [comment]
> I'd like to skim the commit messages to check what updated, so that I can check upstream and see if the updates might be bad.

Shouldn't `-l` be enough for that?

> What I discovered while writing my script is that the database contents also change if there are no changes to the sources. I don't think this should be committed, do you know why that happens? Simply a timestamp?

Well, this is a bit confusing, because shake build system records the internal details of each invocation to the database even if there is no package to update, and such details which may be redundant for us cause the change of the database file. I don't know if there is a seamless workaround, but we can check the changelog to know if we need commit the database file this time.

**Comment by TLATER** [comment]
> Shouldn't `-l` be enough for that?

Well, that output needs to go to the commit message, and if the database isn't committed then the logs won't be created correctly :)

**Comment by berberman** [comment]
So my workflow is always committing all files if changelog is not empty; otherwise don't commit at all. I could add a CLI option for that, do you think it's enough?

**Comment by TLATER** [comment]
That's what I'd like, yeah - Ideally the commits would look similar to [this one](https://github.com/TLATER/dotfiles/commit/9bd38fd5945d26dda59aafe2621bc5c419d713bb).

That message looks close to [what `nix flake update --commit-lock-file` produces](https://github.com/TLATER/dotfiles/commit/a808eb3d43779b2e9d403e8c3b57c50fcb179302).

**Comment by TLATER** [comment]
Oh, awesome! Thanks @berberman :)
